### ISSUE TITLE
Theme not matching - newbie here

### ISSUE THREAD

**Issue by ODelibalta** [leslie255/nvim-config#10]
First of all I want to say a sincere thank you for sharing your config and doing all this work with your instructions. I am a beginner to the vim world and they helped me a lot. 

I have nvim and neovide installed. When I open nvim, it shows a white theme and I see some question marks in squares which I think is not normal. I feel like I am missing something unless this looks normal to you. I'd appreciate your help.

Thank you 
![Screen Shot 2022-10-05 at 10 28 35 PM](https://user-images.githubusercontent.com/4956550/194208105-dcf71b92-c0b3-4a9f-82dc-4af003be1e34.png)

**Comment by leslie255** [comment]
This is just a theme I picked, you can change it in `lua/core/theme.lua`. You can also switch between light/dark mode by using the keymap `<leader>vd` (dark) and `<leader>vl` (light), the default leader key is `;`.

For the question marks, they are supposed to be the fancy file and arrow icons, to use these icons you need [Nerd Fonts](https://www.nerdfonts.com), a special kind of font that supports these icons
