### ISSUE TITLE
Not an editor command: PackerInstall

### ISSUE THREAD

**Issue by umnooob** [leslie255/nvim-config#11]
When entering nvim, it first showed below error:
```
Error detected while processing /root/.config/nvim/init.vim:
line    1:
E5108: Error executing lua vim/keymap.lua:0: rhs: expected string|function, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/keymap.lua: in function 'set'
        /root/.config/nvim/lua/core/keymaps.lua:65: in main chunk
        [C]: in function 'require'
        /root/.config/nvim/lua/core/init.lua:24: in main chunk
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```
Then I entered `:PackerInstall`, it showed `Not an editor command: PackerInstall`
Your nvim configuration is very good. I am a novice to nvim, Thank you for any help！

**Comment by ODelibalta** [comment]
Do you have this installed? 

https://github.com/wbthomason/packer.nvim

**Comment by umnooob** [comment]
Thanks for your timely reply!
Following the quickstart, I did clone this repository like this:
```
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim
```
Shall I do more to install packer.nvim?
And these are my current file state:

```bash
root@DESKTOP-V0OVE1O:~# ls  ~/.local/share/nvim/site/pack/packer/start/packer.nvim
Dockerfile  LICENSE  Makefile  README.md  doc  lua  selene.toml  stylua.toml  tests  vim.toml
root@DESKTOP-V0OVE1O:~#  ls ~/.config/nvim/
LICENSE  README.md  init.vim  lua
root@DESKTOP-V0OVE1O:~# ls ~/.config/nvim/lua/
configs  core
```

**Comment by leslie255** [comment]
After you installed `packer.nvim` just do `:PackerInstall` in NeoVim, that should just work right away.

**Comment by umnooob** [comment]
> After you installed `packer.nvim` just do `:PackerInstall` in NeoVim, that should just work right away.

`:PackerInstall` just doesn't work for me. Any problems here?

> When entering nvim, it first showed below error:
> 
> ```
> Error detected while processing /root/.config/nvim/init.vim:
> line    1:
> E5108: Error executing lua vim/keymap.lua:0: rhs: expected string|function, got nil
> stack traceback:
>         [C]: in function 'error'
>         vim/shared.lua: in function 'validate'
>         vim/keymap.lua: in function 'set'
>         /root/.config/nvim/lua/core/keymaps.lua:65: in main chunk
>         [C]: in function 'require'
>         /root/.config/nvim/lua/core/init.lua:24: in main chunk
>         [C]: in function 'require'
>         [string ":lua"]:1: in main chunk
> Press ENTER or type command to continue
> ```
> 
> **Then I entered `:PackerInstall`, it showed `Not an editor command: PackerInstall` Your nvim configuration is very good. I am a novice to nvim, Thank you for any help！**

**Comment by umnooob** [comment]
OK. I checked my neovim version and found it's the newest unstable version(0.9). Now I have uninstalled it and installed the stable version. It's everything OK now!
Thanks for your patience to a rookie :)
