### ISSUE TITLE
貌似<C-;>这个快捷键失效

### ISSUE THREAD

**Issue by rust-kotlin** [leslie255/nvim-config#12]
vim.keymap.set('i', '<C-;>', '::') -- for C++ and Rust

**Comment by leslie255** [comment]
是终端模拟器的问题，在 GUI 里面是正常的。如果要用的话可以在终端模拟器设置里面加个快捷键

**Comment by rust-kotlin** [comment]
我使用的是alacritty，在alacritty.yml中只配置了这两行键绑定，不清楚为什么Ctrl+;会无法正常使用，大佬知道怎么加快捷键吗？
key_binding:
    - { key: V, mods: Control|Shift, action: Paste }
    - { key: C, mods: Control|Shift, action: Copy }

**Comment by leslie255** [comment]
alacritty 我没搞过，不清楚

**Comment by rust-kotlin** [comment]
我查阅了相关资料，发现`Ctrl+Semicolon`不是一个有效的终端快捷键。

> Terminal can't register a Ctrl-; keystroke. It's just not a valid character. If you look at the control characters in the below ascii table, you'll see Ctrl-; is not on the list.

如果要使用可能需要写个ahk脚本手动转换一下。
