### ISSUE TITLE
启动就报错

### ISSUE THREAD

**Issue by swoloka** [leslie255/nvim-config#15]
处理 /Users/gaoXXX/.config/nvim/init.vim 时发生错误:
第    1 行:
E5108: Error executing lua /Users/gaoXXX/.config/nvim/lua/core/plugins.lua
:2: Vim(packadd):E919: Directory not found in 'packpath': "pack/*/opt/packer
.nvim"
stack traceback:
        [C]: in function 'cmd'
        /Users/gaoXXXX/.config/nvim/lua/core/plugins.lua:2: in main chunk
        [C]: in function 'require'
        /Users/gaoXXXX/.config/nvim/lua/core/init.lua:25: in main chunk
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk

**Comment by leslie255** [comment]
要安装 packer.nvim: [wbthomason/packer.nvim#quickstart](https://github.com/wbthomason/packer.nvim#quickstart)

**Comment by wjy0411** [comment]
需要进入nvim后到命令模式输入 :packerInstall
