### ISSUE TITLE
想把左上角的buffer窗口关掉怎么配置？

### ISSUE THREAD

**Issue by Stephan14** [leslie255/nvim-config#17]
![image](https://user-images.githubusercontent.com/13467996/211903066-65ca2872-0595-4390-af30-85b5b3ede372.png)
想在nvim启动时默认不展示buffer list 窗口，该怎么配置？

**Comment by leslie255** [comment]
左右的 panel 都在 `lua/config/ide.lua` 里面，具体参考 [ldelossa/nvim-ide](https://github.com/ldelossa/nvim-ide)
