### ISSUE TITLE
lspsaga.nvim v0.2.3+ has braking changes. Please read the docs and migrate your configuration to the new "setup" function!

### ISSUE THREAD

**Issue by Stephan14** [leslie255/nvim-config#18]
![image](https://user-images.githubusercontent.com/13467996/212341457-7c7ecf8d-8269-4c25-8575-da8702616c38.png)
请问为什么会报这个错误，我尝试根据
![image](https://user-images.githubusercontent.com/13467996/212341655-56fc9d00-0e5f-4f7b-8e6e-30d9e7dcdffa.png)修改l了`nvim/lua/core/plugins.lua`，还是依然报相同的错误

**Comment by shier1** [comment]
大概看了一下楼主的配置，这个报错原因是lspsaga更新了，查一下lspsaga的doc就好了。
如果只是想简单的不报错，在nvim/lua/configs/autocomplete.lua中119行处，修改为saga.setup()即可。

**Comment by Stephan14** [comment]
改了一下，确实是可以了，刚开始没有找到lspsaga可以修改的地方，多谢了
