### ISSUE TITLE
感谢提供好的配置文件尝试，请教出现如下报错怎么解决？

### ISSUE THREAD

**Issue by bjsyjie** [leslie255/nvim-config#19]
Error detected while processing /home/yccytest/.config/nvim/init.vim:         
line    1:                                                                   
lspsaga.nvim v0.2.3+ has breaking changes. Please read the docs and migrate y
our configuration to the new "setup" function!

**Comment by leslie255** [comment]
我还没更新到最新版的 lspsaga，参考 #18
