### ISSUE TITLE
每次进入nvim提示下载tree-sitter-c

### ISSUE THREAD

**Issue by sheye98** [leslie255/nvim-config#23]

**Comment by sheye98** [comment]
看了一下[nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/issues/3232)里面issues，
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/35909223/233894770-53cebb80-fdd6-4bb3-b4a5-dd44e3f14134.png">，我在treesitter.lua加入了这一行，问题解决了，但是不知道会不会有什么影响

**Comment by sheye98** [comment]
![421682307399_ pic](https://user-images.githubusercontent.com/35909223/233895790-01f61290-ed4f-481f-86d9-76a973a2573c.jpg)
新的问题，这又是什么报错，原地去世

**Comment by sheye98** [comment]
google一下这个问题，[https://github.com/neovim/neovim/pull/20487/files/a99669df1c61cbb867a56b63f832c87513aaf034#diff-97a1025f7f83338441026931e13c7d290b607b9dce5c28ebb510ec471fedc085](deprecated.txt)在这个文件上面找了这个这个名称好像替换成了format，修改keymap.lua的第67行formatting为format解决了这个问题。然后出现以下
<img width="1619" alt="image" src="https://user-images.githubusercontent.com/35909223/233906805-2d325ff4-ce67-4411-8d4c-6e1b26667846.png">

**Comment by fanyer** [comment]
@sheye98  https://github.com/akinsho/bufferline.nvim/issues/735 may help

**Comment by sheye98** [comment]
> @sheye98 [akinsho/bufferline.nvim#735](https://github.com/akinsho/bufferline.nvim/issues/735) may help
thanks,this helped me a lot! i noted there lines.
<img width="842" alt="image" src="https://user-images.githubusercontent.com/35909223/233934463-99e36829-7bc7-4580-8339-5de745cb8e02.png">

**Comment by yechenhao-dev** [comment]
I have resolve this issues.
 
keymap.lua  67 vim.lsp.buf.formatting -> vim.lsp.buf.format
bufferline.lua  75              -- show_buffer_default_icon = true, -- whether or not an unrecognised filetype should show a default icon

**Comment by aocsishao** [comment]
@LittleFi987 
<img width="978" alt="截屏2023-05-31 03 00 27" src="https://github.com/leslie255/nvim-config/assets/46165228/62fa2725-ade4-4095-8627-7f9e87ef0c90">
My icon is ?. Do you know how to be right ? Thank you

**Comment by sheye98** [comment]
> @LittleFi987 <img alt="截屏2023-05-31 03 00 27" width="978" src="https://user-images.githubusercontent.com/46165228/242070066-62fa2725-ade4-4095-8627-7f9e87ef0c90.png"> My icon is ?. Do you know how to be right ? Thank you

https://github.com/sheye98/lazyvim-config#icon-and-fonts
