### ISSUE TITLE
安装了Nerd Font，但是starter页面图标只有“设置”显示正确，其他都是问号

### ISSUE THREAD

**Issue by baldricni** [leslie255/nvim-config#25]
其他neovim的图标，包括文件和目录等显示都正常。这是什么情况？

**Comment by baldricni** [comment]
additional info，我打开了~/.local/share/nvim/site/pack/packer/start/aleph-nvim/lua/aleph/themes/dashboard.lua文件，显示除 了Settings的图标正确外，其他都是问号

**Comment by leslie255** [comment]
应该是不同版本的 nerd font，可以在配置里修改图标字符

**Comment by baldricni** [comment]
> 应该是不同版本的 nerd font，可以在配置里修改图标字符

你是说在这个文件“~/.local/share/nvim/site/pack/packer/start/aleph-nvim/lua/aleph/themes/dashboard.lua”中吗？

**Comment by leslie255** [comment]
最新的 commit 里面应该修好了，是因为 Nerd Font V3 有 breaking change。并且现在在 `lua/configs/startscreen.lua` 里可以直接编辑 starter 页面样式了。
