### ISSUE TITLE
关于lspconfig与具体的language server绑定

### ISSUE THREAD

**Issue by zhuangbility111** [leslie255/nvim-config#5]
大佬你好！我想问个问题：如果具体的language server是我自己通过源码安装的（比如C语言的ccls），我发现lsconfig是没办法找到这个language server的，所以他会报错说`Spawning language server with cmd: `ccls` failed. The language server is either not installed, missing from PATH, or not executable.`。我想问下有没有什么方法可以让lspconfig识别到我自己通过源码安装的language server？ 我知道其中一种方法是通过export PATH来解决，但是这个方法太dirty了，有没有可以直接在lsconfig里面改的

**Comment by leslie255** [comment]
可以在 shell 里 alias 一个 ccls 命令，或者把 ccls 连接到 /.local/bin 里，如果一定要自己配置的话就用不了 lspconfig 要自己搞了

**Comment by leslie255** [comment]
具体手动配置参考这个文档：https://neovim.io/doc/user/lsp.html

**Comment by zhuangbility111** [comment]
好的，谢谢了
