### ISSUE TITLE
`<leader>wl` 快捷键冲突

### ISSUE THREAD

**Issue by honbey** [leslie255/nvim-config#8]
hi, `<leader>wl` 这个快捷键冲突了，无法右切窗口，需要改下 89 行的
https://github.com/leslie255/nvim-config/blob/c64fb3f85a4b5a4936edf471e5239a358f048650/lua/core/keymaps.lua#L36
https://github.com/leslie255/nvim-config/blob/c64fb3f85a4b5a4936edf471e5239a358f048650/lua/core/keymaps.lua#L89

**Comment by leslie255** [comment]
我其实几乎没用过 wh wj wk wl 这四个 keymap，直接删掉了
